version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: ./data_collection/Dockerfile
    container_name: mongodb-custom
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=dbcorridas
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongodb_network
    command: mongod --port 27018 --auth

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local